HIDE
tellraw @s[tag=air] {"rawtext":[{"text":"---------------------\n§b"},{"selector":"@s"},{"text":"§r is a level §b"},{"score":{"name": "@s","objective": "level"}},{"text":"§r Airbender. \nThey have §c"},{"score":{"name": "@s","objective": "deaths"}},{"text":"§r deaths, and §a"},{"score":{"name": "@s","objective": "kills"}},{"text":"§r kills."},{"text":"\nTheir build is: §b"},{"score":{"name": "@s","objective": "moveslot1"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot2"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot3"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot4"}},{"text":"§r\n---------------------"}]}
tellraw @s[tag=water] {"rawtext":[{"text":"---------------------\n§b"},{"selector":"@s"},{"text":"§r is a level §b"},{"score":{"name": "@s","objective": "level"}},{"text":"§r Waterbender. \nThey have §c"},{"score":{"name": "@s","objective": "deaths"}},{"text":"§r deaths, and §a"},{"score":{"name": "@s","objective": "kills"}},{"text":"§r kills."},{"text":"\nTheir build is: §b"},{"score":{"name": "@s","objective": "moveslot1"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot2"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot3"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot4"}},{"text":"§r\n---------------------"}]}
tellraw @s[tag=fire] {"rawtext":[{"text":"---------------------\n§b"},{"selector":"@s"},{"text":"§r is a level §b"},{"score":{"name": "@s","objective": "level"}},{"text":"§r Firebender. \nThey have §c"},{"score":{"name": "@s","objective": "deaths"}},{"text":"§r deaths, and §a"},{"score":{"name": "@s","objective": "kills"}},{"text":"§r kills."},{"text":"\nTheir build is: §b"},{"score":{"name": "@s","objective": "moveslot1"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot2"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot3"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot4"}},{"text":"§r\n---------------------"}]}
tellraw @s[tag=earth] {"rawtext":[{"text":"---------------------\n§b"},{"selector":"@s"},{"text":"§r is a level §b"},{"score":{"name": "@s","objective": "level"}},{"text":"§r Earthbender. \nThey have §c"},{"score":{"name": "@s","objective": "deaths"}},{"text":"§r deaths, and §a"},{"score":{"name": "@s","objective": "kills"}},{"text":"§r kills."},{"text":"\nTheir build is: §b"},{"score":{"name": "@s","objective": "moveslot1"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot2"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot3"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot4"}},{"text":"§r\n---------------------"}]}
tellraw @s[tag=avatar] {"rawtext":[{"text":"---------------------\n§b"},{"selector":"@s"},{"text":"§r is a level §b"},{"score":{"name": "@s","objective": "level"}},{"text":"§r Avatar. \nThey have §c"},{"score":{"name": "@s","objective": "deaths"}},{"text":"§r deaths, and §a"},{"score":{"name": "@s","objective": "kills"}},{"text":"§r kills."},{"text":"\nTheir build is: §b"},{"score":{"name": "@s","objective": "moveslot1"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot2"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot3"}},{"text":":"},{"score":{"name": "@s","objective": "moveslot4"}},{"text":"§r\n---------------------"}]}



