HIDE
execute @s[tag=avatar,scores={moveslot6=1}] ~ ~ ~ function moves/air/air_blast
execute @s[tag=avatar,scores={moveslot6=2}] ~ ~ ~ function moves/air/air_launch
execute @s[tag=avatar,scores={moveslot6=3}] ~ ~ ~ function moves/air/air_scooter
execute @s[tag=avatar,scores={moveslot6=4}] ~ ~ ~ function moves/air/air_push
execute @s[tag=avatar,scores={moveslot6=5}] ~ ~ ~ function moves/air/air_vanish
execute @s[tag=avatar,scores={moveslot6=6}] ~ ~ ~ function moves/air/air_rush
execute @s[tag=avatar,scores={moveslot6=7}] ~ ~ ~ function moves/air/air_shockwave
execute @s[tag=avatar,scores={moveslot6=8}] ~ ~ ~ function moves/air/air_tornado
execute @s[tag=avatar,scores={moveslot6=9}] ~ ~ ~ function moves/air/air_seeking_blast
execute @s[tag=avatar,scores={moveslot6=10}] ~ ~ ~ function moves/air/air_pull
execute @s[tag=avatar,scores={moveslot6=11}] ~ ~ ~ function moves/air/air_dodge
execute @s[tag=avatar,scores={moveslot6=12}] ~ ~ ~ function moves/earth/earth_headbutt
execute @s[tag=avatar,scores={moveslot6=13}] ~ ~ ~ function moves/earth/earth_pillar
execute @s[tag=avatar,scores={moveslot6=14}] ~ ~ ~ function moves/earth/earth_shove
execute @s[tag=avatar,scores={moveslot6=15}] ~ ~ ~ function moves/earth/earth_lift
execute @s[tag=avatar,scores={moveslot6=16}] ~ ~ ~ function moves/earth/earth_shield
execute @s[tag=avatar,scores={moveslot6=17}] ~ ~ ~ function moves/earth/earth_spikes
execute @s[tag=avatar,scores={moveslot6=18}] ~ ~ ~ function moves/earth/earth_burrow
execute @s[tag=avatar,scores={moveslot6=19}] ~ ~ ~ function moves/earth/earth_throw
execute @s[tag=avatar,scores={moveslot6=20}] ~ ~ ~ function moves/earth/earth_search
execute @s[tag=avatar,scores={moveslot6=21}] ~ ~ ~ function moves/earth/earth_builder
execute @s[tag=avatar,scores={moveslot6=22}] ~ ~ ~ function moves/earth/earth_hook
execute @s[tag=avatar,scores={moveslot6=23}] ~ ~ ~ function moves/water/water_flood
execute @s[tag=avatar,scores={moveslot6=24}] ~ ~ ~ function moves/water/water_ice_cage
execute @s[tag=avatar,scores={moveslot6=25}] ~ ~ ~ function moves/water/water_ice_throw
execute @s[tag=avatar,scores={moveslot6=26}] ~ ~ ~ function moves/water/water_spear
execute @s[tag=avatar,scores={moveslot6=27}] ~ ~ ~ function moves/water/water_spike
execute @s[tag=avatar,scores={moveslot6=28}] ~ ~ ~ function moves/water/water_rush
execute @s[tag=avatar,scores={moveslot6=29}] ~ ~ ~ function moves/water/water_fountain
execute @s[tag=avatar,scores={moveslot6=30}] ~ ~ ~ function moves/water/water_healing
execute @s[tag=avatar,scores={moveslot6=31}] ~ ~ ~ function moves/water/water_life_drain
execute @s[tag=avatar,scores={moveslot6=32}] ~ ~ ~ function moves/water/water_splash
execute @s[tag=avatar,scores={moveslot6=33}] ~ ~ ~ function moves/water/water_wake
execute @s[tag=avatar,scores={moveslot6=34}] ~ ~ ~ function moves/fire/fire_blast
execute @s[tag=avatar,scores={moveslot6=35}] ~ ~ ~ function moves/fire/fire_circle
execute @s[tag=avatar,scores={moveslot6=36}] ~ ~ ~ function moves/fire/fire_sprint
execute @s[tag=avatar,scores={moveslot6=37}] ~ ~ ~ function moves/fire/fire_launch
execute @s[tag=avatar,scores={moveslot6=38}] ~ ~ ~ function moves/fire/fire_lightning
execute @s[tag=avatar,scores={moveslot6=39}] ~ ~ ~ function moves/fire/fire_magma_floor
execute @s[tag=avatar,scores={moveslot6=40}] ~ ~ ~ function moves/fire/fire_fireball
execute @s[tag=avatar,scores={moveslot6=41}] ~ ~ ~ function moves/fire/fire_jump
execute @s[tag=avatar,scores={moveslot6=42}] ~ ~ ~ function moves/fire/fire_final
execute @s[tag=avatar,scores={moveslot6=43}] ~ ~ ~ function moves/fire/fire_smite
execute @s[tag=avatar,scores={moveslot6=44}] ~ ~ ~ function moves/fire/fire_seeking_blast
execute @s[tag=avatar,scores={moveslot6=45}] ~ ~ ~ function moves/air/air_combo
execute @s[tag=avatar,scores={moveslot6=46}] ~ ~ ~ function moves/earth/earth_combo
execute @s[tag=avatar,scores={moveslot6=47}] ~ ~ ~ function moves/water/water_combo
execute @s[tag=avatar,scores={moveslot6=48}] ~ ~ ~ function moves/fire/fire_combo
execute @s[scores={moveslot6=0,cooldown1=100}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§cYou dont have a move set, use your bending scroll! (slot 6)"}]}
scoreboard players set @s cooldown1 0
