#bridge-file-version: #104
HIDE 
scoreboard players set @s cooldown1 30
tellraw @s[tag=!chatmsgoff] {"rawtext":[{"text":"You used "},{"text":"§bEarth Search"}]}
scoreboard players add @s sub_level 1
execute @s ~~~ detect ~~-1~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"1 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-2~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"2 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-3~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"3 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-4~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"4 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-5~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"5 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-6~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"6 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-7~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"7 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-9~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"9 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-10~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"10 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-11~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"11 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-12~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"12 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-13~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"13 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-14~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"14 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-15~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"15 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-16~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"16 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-17~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"17 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-18~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"18 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-19~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"19 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-20~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"20 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-21~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"21 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-22~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"22 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-23~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"23 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-24~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"24 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-25~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"25 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-26~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"26 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-27~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"27 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-28~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"28 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-29~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"29 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-30~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"30 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-31~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"31 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-32~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"32 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-33~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"33 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-34~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"34 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-35~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"35 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-36~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"36 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-37~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"37 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-38~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"38 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-39~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"39 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-40~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"40 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-41~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"41 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-42~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"42 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-43~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"43 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-44~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"44 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-46~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"45 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-47~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"46 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-48~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"47 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-49~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"48 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-50~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"49 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-51~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"50 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-52~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"51 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-53~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"52 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-54~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"53 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-55~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"54 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-56~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"55 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-57~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"56 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-58~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"57 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-59~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"58 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-60~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"59 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-61~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"61 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-62~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"62 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-63~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"63 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-64~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"64 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-65~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"65 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-66~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"66 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-67~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"67 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-68~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"68 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-69~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"69 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-70~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"70 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-71~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"71 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-72~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"72 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-73~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"73 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-74~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"74 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-75~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"75 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-76~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"76 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-77~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"77 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-78~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"78 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-79~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"79 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-80~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"80 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-81~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"81 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-82~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"82 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-83~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"83 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-84~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"84 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-85~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"85 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-86~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"86 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-87~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"87 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-88~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"88 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-89~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"89 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-90~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"90 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-91~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"91 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-92~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"92 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-93~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"93 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-94~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"94 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-95~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"95 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-96~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"96 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-97~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"97 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-98~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"98 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-99~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"99 blocks below you: "},{"text":"§bDiamond"}]}
execute @s ~~~ detect ~~-100~ diamond_ore -1 tellraw @s {"rawtext":[{"text":"100 blocks below you: "},{"text":"§bDiamond"}]}