#bridge-file-version: #3
execute @s[tag=avatar,scores={moveslot1=1}] ~ ~ ~ function moves/air_blast
execute @s[tag=avatar,scores={moveslot1=2}] ~ ~ ~ function moves/air_launch
execute @s[tag=avatar,scores={moveslot1=3}] ~ ~ ~ function moves/air_scooter
execute @s[tag=avatar,scores={moveslot1=4}] ~ ~ ~ function moves/air_push
execute @s[tag=avatar,scores={moveslot1=5}] ~ ~ ~ function moves/air_vanish
execute @s[tag=avatar,scores={moveslot1=6}] ~ ~ ~ function moves/air_rush
execute @s[tag=avatar,scores={moveslot1=7}] ~ ~ ~ function moves/air_shockwave
execute @s[tag=avatar,scores={moveslot1=8}] ~ ~ ~ function moves/air_tornado
execute @s[tag=avatar,scores={moveslot1=9}] ~ ~ ~ function moves/air_seeking_blast
execute @s[tag=avatar,scores={moveslot1=10}] ~ ~ ~ function moves/air_pull
execute @s[tag=avatar,scores={moveslot1=11}] ~ ~ ~ function moves/air_dodge
execute @s[tag=avatar,scores={moveslot1=12}] ~ ~ ~ function moves/earth_headbutt
execute @s[tag=avatar,scores={moveslot1=13}] ~ ~ ~ function moves/earth_pillar
execute @s[tag=avatar,scores={moveslot1=14}] ~ ~ ~ function moves/earth_shove
execute @s[tag=avatar,scores={moveslot1=15}] ~ ~ ~ function moves/earth_lift
execute @s[tag=avatar,scores={moveslot1=16}] ~ ~ ~ function moves/earth_shield
execute @s[tag=avatar,scores={moveslot1=17}] ~ ~ ~ function moves/earth_spikes
execute @s[tag=avatar,scores={moveslot1=18}] ~ ~ ~ function moves/earth_burrow
execute @s[tag=avatar,scores={moveslot1=19}] ~ ~ ~ function moves/earth_throw
execute @s[tag=avatar,scores={moveslot1=20}] ~ ~ ~ function moves/earth_search
execute @s[tag=avatar,scores={moveslot1=21}] ~ ~ ~ function moves/earth_builder
execute @s[tag=avatar,scores={moveslot1=22}] ~ ~ ~ function moves/earth_hook
execute @s[tag=avatar,scores={moveslot1=23}] ~ ~ ~ function moves/water_flood
execute @s[tag=avatar,scores={moveslot1=24}] ~ ~ ~ function moves/water_ice_cage
execute @s[tag=avatar,scores={moveslot1=25}] ~ ~ ~ function moves/water_ice_throw
execute @s[tag=avatar,scores={moveslot1=26}] ~ ~ ~ function moves/water_spear
execute @s[tag=avatar,scores={moveslot1=27}] ~ ~ ~ function moves/water_spike
execute @s[tag=avatar,scores={moveslot1=28}] ~ ~ ~ function moves/water_rush
execute @s[tag=avatar,scores={moveslot1=29}] ~ ~ ~ function moves/water_fountain
execute @s[tag=avatar,scores={moveslot1=30}] ~ ~ ~ function moves/water_healing
execute @s[tag=avatar,scores={moveslot1=31}] ~ ~ ~ function moves/water_life_drain
execute @s[tag=avatar,scores={moveslot1=32}] ~ ~ ~ function moves/water_splash
execute @s[tag=avatar,scores={moveslot1=33}] ~ ~ ~ function moves/water_wake
execute @s[tag=avatar,scores={moveslot1=34}] ~ ~ ~ function moves/fire_blast
execute @s[tag=avatar,scores={moveslot1=35}] ~ ~ ~ function moves/fire_circle
execute @s[tag=avatar,scores={moveslot1=36}] ~ ~ ~ function moves/fire_sprint
execute @s[tag=avatar,scores={moveslot1=37}] ~ ~ ~ function moves/fire_launch
execute @s[tag=avatar,scores={moveslot1=38}] ~ ~ ~ function moves/fire_lightning
execute @s[tag=avatar,scores={moveslot1=39}] ~ ~ ~ function moves/fire_magma_floor
execute @s[tag=avatar,scores={moveslot1=40}] ~ ~ ~ function moves/moves/fire_fireball
execute @s[tag=avatar,scores={moveslot1=41}] ~ ~ ~ function moves/fire_jump
execute @s[tag=avatar,scores={moveslot1=42}] ~ ~ ~ function moves/fire_final
execute @s[tag=avatar,scores={moveslot1=43}] ~ ~ ~ function moves/fire_smite
execute @s[tag=avatar,scores={moveslot1=44}] ~ ~ ~ function moves/fire_seeking_blast
execute @s[scores={moveslot1=0,cooldown1=100}] ~ ~ ~ tellraw @s {"rawtext":[{"text":"§cYou dont have a move set, use /function useful_tools (slot 1)"}]}
scoreboard players set @s cooldown1 0