execute @s[tag=chooseslot1,scores={detect_left=1,detect_sneak=0}] ~ ~ ~ scoreboard players add @s chooseslot 1
execute @s[tag=chooseslot1,scores={detect_left=1}] ~ ~ ~ scoreboard players set @s detect_left 0
#execute @s[tag=chooseslot1] ~ ~ ~ function assets/choose_menu
execute @s[tag=chooseslot1,scores={chooseslot=45..}] ~ ~ ~ scoreboard players set @s chooseslot 1
execute @s[scores={detect_sneak=1}] ~ ~ ~ titleraw @s actionbar {"rawtext":[{"text":"§3You chose the move for slot 1!"}]}
 
execute @s[tag=chooseslot1,scores={chooseslot=1,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 1
execute @s[tag=chooseslot1,scores={chooseslot=2,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 2
execute @s[tag=chooseslot1,scores={chooseslot=3,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 3
execute @s[tag=chooseslot1,scores={chooseslot=4,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 4
execute @s[tag=chooseslot1,scores={chooseslot=5,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 5
execute @s[tag=chooseslot1,scores={chooseslot=6,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 6
execute @s[tag=chooseslot1,scores={chooseslot=7,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 7
execute @s[tag=chooseslot1,scores={chooseslot=8,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 8
execute @s[tag=chooseslot1,scores={chooseslot=9,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 9
execute @s[tag=chooseslot1,scores={chooseslot=10,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 10
execute @s[tag=chooseslot1,scores={chooseslot=11,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 11
execute @s[tag=chooseslot1,scores={chooseslot=12,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 12
execute @s[tag=chooseslot1,scores={chooseslot=13,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 13
execute @s[tag=chooseslot1,scores={chooseslot=14,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 14
execute @s[tag=chooseslot1,scores={chooseslot=15,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 15
execute @s[tag=chooseslot1,scores={chooseslot=16,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 16
execute @s[tag=chooseslot1,scores={chooseslot=17,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 17
execute @s[tag=chooseslot1,scores={chooseslot=18,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 18
execute @s[tag=chooseslot1,scores={chooseslot=19,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 19
execute @s[tag=chooseslot1,scores={chooseslot=20,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 20
execute @s[tag=chooseslot1,scores={chooseslot=21,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 21
execute @s[tag=chooseslot1,scores={chooseslot=22,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 22
execute @s[tag=chooseslot1,scores={chooseslot=23,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 23
execute @s[tag=chooseslot1,scores={chooseslot=24,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 24
execute @s[tag=chooseslot1,scores={chooseslot=25,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 25
execute @s[tag=chooseslot1,scores={chooseslot=26,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 26
execute @s[tag=chooseslot1,scores={chooseslot=27,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 27
execute @s[tag=chooseslot1,scores={chooseslot=28,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 28
execute @s[tag=chooseslot1,scores={chooseslot=29,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 29
execute @s[tag=chooseslot1,scores={chooseslot=30,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 30
execute @s[tag=chooseslot1,scores={chooseslot=31,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 31
execute @s[tag=chooseslot1,scores={chooseslot=32,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 32
execute @s[tag=chooseslot1,scores={chooseslot=33,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 33
execute @s[tag=chooseslot1,scores={chooseslot=34,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 34
execute @s[tag=chooseslot1,scores={chooseslot=35,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 35
execute @s[tag=chooseslot1,scores={chooseslot=36,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 36
execute @s[tag=chooseslot1,scores={chooseslot=37,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 37
execute @s[tag=chooseslot1,scores={chooseslot=38,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 38
execute @s[tag=chooseslot1,scores={chooseslot=39,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 39
execute @s[tag=chooseslot1,scores={chooseslot=40,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 40
execute @s[tag=chooseslot1,scores={chooseslot=41,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 41
execute @s[tag=chooseslot1,scores={chooseslot=42,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 42
execute @s[tag=chooseslot1,scores={chooseslot=43,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 43
execute @s[tag=chooseslot1,scores={chooseslot=44,detect_sneak=1}] ~ ~ ~ scoreboard players set @s moveslot1 44
